import './room-details.scss'
import '../../blocks/header/header'
import '../../blocks/select/select'
import '../../blocks/card-booking/card-booking'
import '../../blocks/like-button/like-button'
import '../../blocks/card-comment/card-comment'
