import './index.scss'
import * as $ from 'jquery'
import '../cards/cards'
import '../headers-and-footers/headers-and-footers'
import '../form-elements/form-elements'
import '../colors-and-type/colors-and-type'
